
<? 
// 定義通用頁面頭部 
include("common.inc");
?> 
<HTML> 
<HEAD> 
<script type="text/javascript" src="/js/jquery-1.5.1.js"></script> 
<script type="text/javascript" src="/js/jquery-ui-1.8.14.custom.min.js"></script>
<script type="text/javascript" src="tree.js"></script>
<meta http-equiv="content-type" content="text/html; charset=big5">
<TITLE> 
<? echo "案件編號隨案費用及案件收入系統".$title; ?> 
</TITLE> 
</HEAD> 
<BODY> 
